<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Papst.EventStore.AzureCosmos</PackageId>
    <Title>Papst EventStore Azure Cosmos DB</Title>
    <Description>Azure Cosmos DB based EventStore implementation for Papst.EventStore.</Description>
    <PackageTags>eventsourcing;eventstore;cosmosdb;azure;cqrs</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Papst.EventStore\Papst.EventStore.csproj" Condition="'$(Configuration)' == 'DEBUG'" />
    <PackageReference Include="Papst.EventStore" Condition="'$(Configuration)' != 'DEBUG'" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>
